### ISSUE TITLE
Скрыть новости

### ISSUE THREAD

**Issue by Potsanchik** [Amaimersion/2ch-helper#35]
Можешь добавить возможность скрыть новости под всеми тредами, т.е. надписи "Топ за час • Топ за сегодня • Последние 10" и то, что под ними?

**Comment by Amaimersion** [comment]
Сделаю. Скрываться будет все, кроме формы для жалоб и информации.
Алсо, это также можно делать любым блокировщиком рекламы.
![screenshot_1](https://user-images.githubusercontent.com/20613502/42940454-2de03a1c-8b62-11e8-8d54-63a1af328763.jpg)

**Comment by Potsanchik** [comment]
Да, ты прав, я долбоёб, походу.

**Comment by Amaimersion** [comment]
@Potsanchik Все еще нужно?

**Comment by Potsanchik** [comment]
Нет.
